### PR TITLE
Mig17.0 purchase_requisition_incoterm

### PR DESCRIPTION
**Pull request by laszlokr**

### CODE REVIEW

**Review by janikvonrotz — COMMENTED** [review]
Is this module still required in 17?

I think this is a copy of an OCA module.

**Comment by laszlokr** [comment]
@janikvonrotz yes, it's needed. I think the incoterm functionality is included for purchase orders, but not for blanket orders. In OCA there is no such module and this is not a copy of one, it's a Mint System module

**Comment by janikvonrotz** [comment]
@laszlokr It should be a copy of OCA module because of the translation fiels.

Can you remove the translation files, except de?

**Comment by laszlokr** [comment]
@janikvonrotz sorry there was some confusion about which module you are referring to. The `purchase_requisition_incoterm` is our module and is needed, but `purchase_partner_incoterm` is indeed a copy of OCA module which somehow ended up here. Apologies for that, I will remove it now

**Review by janikvonrotz — APPROVED** [review]

**Pull request merged**
