### PR TITLE
feat: make notes fields editable

### PR DESCRIPTION
**Pull request by laszlokr**

### CODE REVIEW

**Review by janikvonrotz — COMMENTED** [review]
The fields should be editable by default. Why is this not the case?

**Comment by laszlokr** [comment]
> The fields should be editable by default. Why is this not the case?

@janikvonrotz  Yes, these are editable by default, but for some reason on the installations for Tissa and Trimada they are readonly, so the only solution was to explicitly set it. Same for the sale_order_notes module

**Comment by janikvonrotz** [comment]
@laszlokr I suggest that you try to find the cause. You can check the field definition and form views.

**Comment by janikvonrotz** [comment]
Fix it in `sale_order_template_notes` and `purchase_requisition_notes`.

**Pull request closed without merging**
